
//Number of projects in this VS solution:  5


// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;




[assembly: AssemblyVersion("5.9.2020.884")]
[assembly: AssemblyFileVersion("5.9.2020.884")]
